config:
  aws:region: us-east-1
  setup-s3-auditlogs:logsBaseName: demoOrgAuditLogs
  setup-s3-auditlogs:orgName: demo
  setup-s3-auditlogs:pulumiApiKey:
    secure: AAABAMh4qXfNJXY52d1QBnG8R26bVf+6L+qUhbDo/DV9RR9dH16sMyRk5VNZeAkqg8p6VkRCQmBeW8Ut8ZtjkXnUPV+ej97WQWe/Bw==
