import json

# The azure_resources_file should be generated using az resource list --resource-group <resource_group> 
azure_resources_file = 'azure-resources.json'

# The type_mappings_file is predefined and contains a mapping of Azure resource types to the corresponding Pulumi types.
# It could probably be generated by a script but for now just make sure it contains mappings for all the types in the azure_resources_file
# being processed.
type_mappings_file = 'type-mappings.json'

# This is the bulk imoprt file that will be generated.
bulk_import_file = 'bulk-import.json'

# Load the azure resources json
try:
    with open(azure_resources_file, 'r') as file:
        azure_resources = json.load(file)
except FileNotFoundError:
    print(f"Error: File, {azure_resources_file}, not found.")
except json.JSONDecodeError:
    print(f"Error: Invalid JSON format in file, {azure_resources_file}.")
except Exception as e:
    print(f"An unexpected error occurred while reading {azure_resources_file}: {e}")

# Load the type mappings json
try:
    with open(type_mappings_file, 'r') as file:
        type_mappings = json.load(file)
except FileNotFoundError:
    print(f"Error: File, {type_mappings_file}, not found.")
except json.JSONDecodeError:
    print(f"Error: Invalid JSON format in file, {type_mappings_file}.")
except Exception as e:
    print(f"An unexpected error occurred while reading {type_mappings_file}: {e}")

bulk_resources = []
for resource in azure_resources:
    resource_type = resource['type']
    if resource_type in type_mappings:
        # Build a given resource's bulk import object
        # See https://www.pulumi.com/docs/iac/adopting-pulumi/import/#bulk-import-operations for format
        pulumi_type = type_mappings[resource_type]
        pulumi_name = pulumi_type.split(':')[-1]
        azure_id = resource['id']
        bulk_resources.append({
            "type": pulumi_type,
            "name": pulumi_name,
            "id": azure_id
        })
    else:
        print(f"Error: No Pulumi type found in {type_mappings_file} for Azure resource type: {resource_type}")

bulk_resources = {
    "resources": bulk_resources
}
pretty_json = json.dumps(bulk_resources, indent=4)
print(pretty_json)
    

